---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Ensure necessary packages are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is started and enabled on boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Set up Docker GCP auth helper
  ansible.builtin.command: "gcloud auth configure-docker --quiet {{ gcp_repo_host }}"
  when: gcp_repo_host
